apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: red-hat-design-system
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: red-hat-design-system
    app.kubernetes.io/part-of: red-hat-design-system
  name: red-hat-design-system
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: red-hat-design-system
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: red-hat-design-system
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/bepowers-tenant/red-hat-design-system/red-hat-design-system@sha256:3f70b8ef774055e0319c8b6b3480007c9aa8166ba79d316420f29458b508334e
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
