apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: red-hat-design-system
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: red-hat-design-system
    app.kubernetes.io/part-of: red-hat-design-system
  name: red-hat-design-system
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: red-hat-design-system
status:
  loadBalancer: {}
