apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: red-hat-design-system
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/bepowers-tenant/red-hat-design-system/red-hat-design-system@sha256:e9da41b8b32a54eec6971c1c723951de398394166a03985d0b0eeb8f574d57e3
        name: my-nodejs
        resources: {}
status: {}
